cameras:
  back:
    hostname: firecamback.local
    port: 81
    stream_path: /back/stream
  front:
    hostname: firecamfront.local
    port: 80
    stream_path: /front/stream
  left:
    hostname: firecamleft.local
    port: 82
    stream_path: /left/stream
  right:
    hostname: firecamright.local
    port: 83
    stream_path: /right/stream
email:
  alert_types:
  - smoke
  - fire
  app_pass: kusw ujez lwkm vtud
  enable: true
  interval: 60
  receiver:
  - yyy@gmail.com
  - xxx@gmail.com
  sender: multifireextinguisher@gmail.com
file_handling:
  csv_header:
  - datetime
  - camera
  - event
  - confidence_level
  max_records: 1200
  record_update: 5
motor:
  autonomous_mode: false
  hostname: firecamfront.local
  path: /front/motor
  port: 80
stream:
  frame_interval: 0.2
  inference_every_n: 5
  jpeg_quality: 60
  target_fps: 15.0
